name: Ci Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: ./server
        run: npm i

      - name: Run tests
        working-directory: ./server
        run: npm test

      - name: Install Client dependencies
        working-directory: ./client
        run: npm i

      - name: Build Client
        working-directory: ./client
        run: npm run build
